name = "EvalMetrics"
uuid = "251d5f9e-10c1-4699-ba24-e0ad168fa3e4"
authors = ["Vaclav Macha <vaclav.macha92@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DocStringExtensions = "^0.8"
RecipesBase = "^1.0"
StatsBase = "^0.33"
julia = "^1.0"
